[package]
name = "rudicom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.5"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
serde_json = "1.0"
