[package]
name = "rudicom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.6"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
serde_json = "1.0"
surrealdb = "1.0.0-beta.9"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.29", features = ["macros", "rt-multi-thread", "fs"] }
glob = "0.3"
once_cell = "1"
config = {version = "0.13", features = ["toml"]}
md5 = "0.7.0"
