[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
clap = "4.4"
dicom = "0.6"
tokio = "1.35"
anyhow = "1.0"
