name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Build binaries in "release" mode
        run: cargo build -r
      - name: Run tests
        run: cargo test --verbose
      - name: create release
        run: gh release create --generate-notes "${{  github.ref_name }}" "target/release/rudicom#Ubuntu-latest"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
